"""
StoneVision AI  -  PDF Catalog Generator v4.0 FINAL
====================================================
Every PDF carries:
  - Customer company name + city  (header, every page)
  - StoneVision branding + website (footer, every page, cannot be removed)
  - Full legal disclaimer  (body, every page)
  - Copyright notice  (footer, every page)
  - Powered-by block  (body, bottom)

All text ASCII-safe  -  no encoding crashes.
Uses: fpdf2, qrcode, Pillow
"""
from __future__ import annotations
import io
from datetime import datetime, timezone
from fpdf import FPDF, XPos, YPos
import qrcode

# Brand colours (RGB)
GOLD   = (201, 168,  76)
GOLD_D = (140, 108,  40)
DARK   = ( 26,  23,  20)
MID    = ( 60,  55,  45)
GRAY   = ( 90,  85,  75)
LGRAY  = (240, 235, 224)
WHITE  = (255, 255, 255)
RED    = (180,  40,  30)
GREEN  = ( 39, 148,  80)
AMBER  = (200, 130,  20)

# StoneVision business identity  (update these to your real details)
SV_BRAND    = "StoneVision AI"
SV_WEBSITE  = "www.stonevision.in"
SV_EMAIL    = "support@stonevision.in"
SV_CITY     = "Madurai, Tamil Nadu, India"
SV_TAGLINE  = "Granite Intelligence for Melur-Madurai Exporters"


class CatalogPDF(FPDF):
    def __init__(self, co_name, co_city, co_whatsapp="", is_verified=False):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.co_name     = (co_name or "Granite Exporter")[:60]
        self.co_city     = (co_city or "Melur")[:30]
        self.co_whatsapp = co_whatsapp or ""
        self.is_verified = is_verified
        self.set_auto_page_break(auto=True, margin=24)
        self.set_margins(14, 14, 14)

    def header(self):
        # Gold top stripe
        self.set_fill_color(*GOLD)
        self.rect(0, 0, 210, 6, style="F")
        self.set_y(9)
        # Customer company name - large and prominent
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*DARK)
        self.cell(0, 7, self.co_name.upper(), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        # City + verified
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*GRAY)
        badge = "  [StoneVision Certified]" if self.is_verified else ""
        self.cell(0, 4,
                  f"Granite Exporters  |  {self.co_city}, Tamil Nadu{badge}",
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        # Divider
        self.set_draw_color(*GOLD)
        self.set_line_width(0.5)
        self.line(14, self.get_y() + 2, 196, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-22)
        # Legal warning in red
        self.set_font("Helvetica", "B", 6)
        self.set_text_color(*RED)
        self.cell(0, 4,
                  "AI ESTIMATE ONLY  -  NOT a certified measurement. "
                  "Verify independently before any commercial use.",
                  align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        # StoneVision attribution  (always present - your brand on every PDF)
        self.set_font("Helvetica", "", 6)
        self.set_text_color(*GRAY)
        self.cell(0, 4,
                  f"Generated by {SV_BRAND}  |  {SV_WEBSITE}  |  {SV_EMAIL}  |  {SV_CITY}",
                  align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        # Page + date + copyright
        self.set_font("Helvetica", "", 5.5)
        self.set_text_color(*MID)
        today = datetime.now(timezone.utc).strftime("%d %b %Y")
        yr    = datetime.now(timezone.utc).year
        self.cell(0, 3.5,
                  f"Page {self.page_no()}  |  {today}  |  "
                  f"Copyright (c) {yr} {SV_BRAND}. All rights reserved.",
                  align="C")


def generate_catalog_pdf(stone: dict, company: dict) -> bytes:
    """Generate branded A4 PDF. Returns bytes."""

    # Safe field extractors
    def _s(k, d=""):
        v = stone.get(k)
        return str(v).strip() if v is not None else d

    def _f(k, d=0.0):
        try:
            v = float(stone.get(k) or d)
            return d if v != v else v   # NaN check
        except (TypeError, ValueError):
            return d

    def _i(k, d=0):
        try:
            v = stone.get(k)
            return int(v) if v is not None else d
        except (TypeError, ValueError):
            return d

    # Extract all stone fields safely
    scan_code = _s("scan_code", "SV-UNKNOWN")
    variety   = _s("variety",   "Unknown Granite")
    grade     = _s("quality_grade", "A2")
    grade     = grade if grade in ("A1","A2","B1","B2") else "A2"
    L, W, H   = _f("length_cm"), _f("width_cm"), _f("height_cm")
    vol_m3    = _f("volume_m3");  vol_cft = _f("volume_cft")
    weight    = _i("estimated_weight_kg")
    vpf       = _i("value_per_cft_inr")
    total_val = _i("total_value_inr")
    markets   = ", ".join(stone.get("export_markets") or []) or "-"
    quality_n = _s("quality_notes", "-")
    reasoning = _s("variety_reasoning", "")
    pub_link  = _s("public_link", "")
    scanned_at= (_s("scanned_at", "")[:10] or "-")
    stick_ok  = stone.get("reference_stick_ok", True)
    ai_flags  = [f for f in (stone.get("ai_flags") or []) if isinstance(f, str)]

    # Confidence (handle 0.0-1.0 OR 0-100 formats)
    _vc = _f("variety_confidence", 0)
    _mc = _f("measurement_confidence", 0)
    v_conf = max(0, min(int(_vc if _vc > 1 else _vc * 100), 100))
    m_conf = max(0, min(int(_mc if _mc > 1 else _mc * 100), 100))

    # Company fields
    co_name     = (company.get("name") or "Granite Exporter")[:60]
    co_city     = (company.get("city") or "Melur")[:30]
    co_whatsapp = str(company.get("whatsapp") or "")
    is_verified = bool(company.get("is_verified", False))

    # Build PDF
    pdf = CatalogPDF(co_name, co_city, co_whatsapp, is_verified)
    pdf.add_page()

    # -- Scan ID + Variety ------------------------------------------
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*GOLD_D)
    pdf.cell(0, 5, f"STONE CATALOG  |  #{scan_code}",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*DARK)
    pdf.cell(0, 10, variety, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*GRAY)
    pdf.cell(0, 4.5,
             f"Scanned: {scanned_at}  |  "
             f"AI Confidence: {v_conf}% variety  /  {m_conf}% measurement",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # -- Grade badge -----------------------------------------------
    badge_col = GREEN if grade=="A1" else AMBER if grade=="A2" else RED
    pdf.set_fill_color(*badge_col)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(30, 7, f"  Grade {grade}", fill=True)
    pdf.set_text_color(*GRAY)
    pdf.set_font("Helvetica", "", 8)
    grade_lbl = {"A1":"Export Ready - Top Quality",
                 "A2":"Exportable with Disclosure",
                 "B1":"Domestic Market Only",
                 "B2":"Domestic / Scrap Grade"}.get(grade, "")
    pdf.cell(0, 7, f"  {grade_lbl}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(6)

    # -- AI Flag warnings ------------------------------------------
    if ai_flags:
        pdf.set_fill_color(255, 235, 220)
        pdf.set_draw_color(*RED)
        pdf.set_line_width(0.3)
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(*RED)
        flag_txt = "  AI FLAGS: " + "  |  ".join(f.replace("_"," ") for f in ai_flags)
        pdf.cell(0, 6, flag_txt[:90], fill=True, border=1,
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(4)

    # -- Dimensions ------------------------------------------------
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*GRAY)
    pdf.cell(0, 5, "ESTIMATED DIMENSIONS  (AI  -  +/-5 to 15% error margin)",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(1)
    for lbl, val in [("LENGTH", L), ("WIDTH", W), ("HEIGHT", H)]:
        _dim_box(pdf, lbl, f"{val:.1f}" if val else "-", "cm")
    pdf.ln(22)

    # -- Details table ---------------------------------------------
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*GRAY)
    pdf.cell(0, 5, "BLOCK DETAILS", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(1)
    rows = [
        ("Volume",         f"{vol_m3} m3  /  {vol_cft} cft"),
        ("Est. Weight",    f"{weight:,} kg" if weight else "-"),
        ("Est. Value",     f"Rs.{vpf:,}/cft  |  Rs.{total_val/100000:.1f}L total" if vpf else "-"),
        ("Export Markets", markets),
        ("Quality Notes",  quality_n[:80] if quality_n else "-"),
        ("Ref. Stick",     "Detected" if stick_ok else "NOT detected - verify dims manually"),
        ("AI Source",      "Google Gemini 1.5 Flash Vision"),
        ("Platform",       f"{SV_BRAND}  |  {SV_WEBSITE}"),
    ]
    for i, (k, v) in enumerate(rows):
        bg = LGRAY if i % 2 == 0 else WHITE
        pdf.set_fill_color(*bg)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*GRAY)
        pdf.cell(55, 6, f"  {k}", fill=True)
        pdf.set_text_color(*DARK)
        pdf.cell(0, 6, f"  {v}", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(5)

    # -- AI Reasoning ----------------------------------------------
    if reasoning:
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*GRAY)
        pdf.cell(0, 5, "AI VARIETY REASONING", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "I", 7.5)
        pdf.set_text_color(*MID)
        pdf.multi_cell(0, 4.5, reasoning[:300])
        pdf.ln(3)

    # -- QR code ---------------------------------------------------
    if pub_link:
        qr_y = pdf.get_y()
        try:
            buf = _make_qr(pub_link)
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*GRAY)
            pdf.cell(145, 5, "VERIFY ONLINE  -  Scan QR code or visit link",
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_font("Helvetica", "", 7.5)
            pdf.set_text_color(*DARK)
            pdf.cell(145, 5, pub_link[:72], new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.image(buf, x=157, y=qr_y, w=40, h=40)  # MODULE 3: Larger QR for clean scanning
        except Exception:
            pass
        pdf.ln(8)

    # -- Legal disclaimer box -------------------------------------
    pdf.set_fill_color(255, 244, 244)
    pdf.set_draw_color(*RED)
    pdf.set_line_width(0.4)
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_text_color(*RED)
    pdf.cell(0, 6, "  ! IMPORTANT LEGAL DISCLAIMER  -  READ BEFORE USE",
             fill=True, border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(*GRAY)
    pdf.multi_cell(0, 4.5,
        "  All dimension estimates, variety identifications, quality grades, weights, "
        "and value estimates in this document are ARTIFICIAL INTELLIGENCE ESTIMATES "
        "generated from photographic analysis using Google Gemini Vision. These are "
        "NOT certified measurements, geological surveys, or professional appraisals. "
        "Error margin: +/-5 to +/-15 percent depending on image quality and conditions.\n\n"
        "  This document MUST NOT be used as the sole basis for commercial contracts, "
        "export invoices, letters of credit, customs declarations, shipping bills, or "
        "any legally binding agreement. All measurements must be verified independently "
        "by a certified quarry professional before commercial use.\n\n"
        "  StoneVision AI and its operators accept NO liability for commercial disputes, "
        "financial losses, or export regulation violations arising from reliance on these "
        "AI-estimated outputs. Full terms: www.stonevision.in/terms",
        border=1, fill=True)
    pdf.ln(4)

    # -- Powered-by block (your brand, always visible) -------------
    pdf.set_fill_color(*DARK)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*GOLD)
    pdf.cell(0, 6, f"  {SV_BRAND}  -  {SV_TAGLINE}",
             fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(*LGRAY)
    pdf.cell(0, 5,
             f"  {SV_WEBSITE}  |  {SV_EMAIL}  |  Scan: #{scan_code}",
             fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output())


def _dim_box(pdf: FPDF, label: str, value: str, unit: str):
    x, y, w = pdf.get_x(), pdf.get_y(), 54
    pdf.set_fill_color(*LGRAY)
    pdf.rect(x, y, w-3, 18, style="F")
    pdf.set_draw_color(*GOLD)
    pdf.set_line_width(0.2)
    pdf.rect(x, y, w-3, 18)
    pdf.set_xy(x, y+1)
    pdf.set_font("Helvetica", "", 6.5); pdf.set_text_color(*GRAY)
    pdf.cell(w-3, 4, label, align="C")
    pdf.set_xy(x, y+5.5)
    pdf.set_font("Helvetica", "B", 14); pdf.set_text_color(*DARK)
    pdf.cell(w-3, 7, value, align="C")
    pdf.set_xy(x, y+13)
    pdf.set_font("Helvetica", "", 6.5); pdf.set_text_color(*GRAY)
    pdf.cell(w-3, 4, f"({unit}  -  AI estimate)", align="C")
    pdf.set_xy(x+w, y)


def _make_qr(url: str, size: int = 400) -> io.BytesIO:
    """
    MODULE 3 FIX: High-resolution QR code generation.
    - box_size=10 → ~290px native, scaled to `size` for crisp rendering
    - border=4    → proper quiet zone (ISO 18004 minimum is 4 modules)
    - ERROR_CORRECT_H → 30% redundancy — survives partial damage/blur
    - Resized to exactly `size`×`size` px before embedding in PDF
    """
    from PIL import Image as PILImage

    qr = qrcode.QRCode(
        version=None,                              # auto-select smallest version
        error_correction=qrcode.constants.ERROR_CORRECT_H,  # highest redundancy
        box_size=10,                               # 10px per module → crisp
        border=4,                                  # 4-module quiet zone (ISO spec)
    )
    qr.add_data(url)
    qr.make(fit=True)

    img = qr.make_image(fill_color=(0, 0, 0), back_color=(255, 255, 255))
    pil_img = img.get_image() if hasattr(img, "get_image") else img.convert("RGB")

    # Scale to exact target size with LANCZOS for sharpness
    pil_img = pil_img.resize((size, size), PILImage.LANCZOS)

    # Add 8px white padding to ensure quiet zone is never clipped by PDF renderer
    padded_size = size + 16
    padded = PILImage.new("RGB", (padded_size, padded_size), (255, 255, 255))
    padded.paste(pil_img, (8, 8))

    buf = io.BytesIO()
    padded.save(buf, format="PNG", dpi=(300, 300), optimize=False)
    buf.seek(0)
    return buf
