"""
StoneVision AI — Multilingual PDF Service v1.0
================================================
Generates export catalog PDF in 5 languages:
  EN - English (default)
  TA - Tamil (India)
  AR - Arabic (Middle East/Gulf)
  ZH - Chinese Simplified (China)
  PL - Polish (Europe)

Foreign buyers see their language.
Indian exporter always appears at top.
StoneVision AI branding on every page.
"""
from __future__ import annotations
import io
import os
from datetime import datetime, timezone
from fpdf import FPDF, XPos, YPos

# ── Native Unicode Font Paths (module level) ───────────────────
_FONT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fonts")
FONTS = {
    "EN": os.path.join(_FONT_DIR, "NotoSans-Regular.ttf"),
    "PL": os.path.join(_FONT_DIR, "NotoSans-Regular.ttf"),
    "TA": os.path.join(_FONT_DIR, "NotoSansTamil-Regular.ttf"),
    "AR": os.path.join(_FONT_DIR, "NotoSansArabic-Regular.ttf"),
    "ZH": os.path.join(_FONT_DIR, "NotoSansCJK-Regular.ttc"),
}
FONT_NAMES = {
    "EN": "NotoSans",
    "PL": "NotoSans",
    "TA": "NotoTamil",
    "AR": "NotoArabic",
    "ZH": "NotoSC",
}
import qrcode

# ── Brand ────────────────────────────────────────────────────
SV_BRAND   = "StoneVision AI"
SV_WEBSITE = "www.stonevision.in"
SV_EMAIL   = "support@stonevision.in"
SV_CITY    = "Madurai, Tamil Nadu, India"

# ── Colors ───────────────────────────────────────────────────
GOLD  = (201, 168,  76)
DARK  = ( 26,  23,  20)
GRAY  = ( 90,  85,  75)
LGRAY = (240, 235, 224)
WHITE = (255, 255, 255)
RED   = (180,  40,  30)
GREEN = ( 39, 148,  80)
AMBER = (200, 130,  20)

# ── Translations ─────────────────────────────────────────────
# All non-ASCII chars replaced with ASCII equivalents for fpdf2
TRANSLATIONS = {
    "EN": {
        "catalog_title":     "GRANITE BLOCK CATALOG",
        "ai_verified":       "AI VERIFIED",
        "powered_by":        "Powered by Google Gemini Vision AI",
        "exporter":          "Exporter",
        "scan_id":           "Scan ID",
        "variety":           "Stone Variety",
        "grade":             "Quality Grade",
        "length":            "Length (est.)",
        "width":             "Width (est.)",
        "height":            "Height (est.)",
        "volume":            "Volume (est.)",
        "weight":            "Est. Weight",
        "value":             "Est. Value",
        "markets":           "Export Markets",
        "confidence":        "AI Confidence",
        "variety_conf":      "Variety ID",
        "dims_conf":         "Dimensions",
        "reference_stick":   "Reference Stick",
        "detected":          "Detected",
        "not_detected":      "Not detected - verify",
        "verify_online":     "VERIFY ONLINE",
        "scan_qr":           "Scan QR code to verify this certificate online",
        "disclaimer_title":  "IMPORTANT DISCLAIMER",
        "disclaimer_body":   (
            "All dimensions, variety identifications and value estimates are "
            "AI-generated from photographic analysis using Google Gemini Vision. "
            "These are ESTIMATES ONLY - not certified measurements. "
            "Error margin: +/-5% to +/-15%. "
            "Must be independently verified before any commercial contract, "
            "Letter of Credit, or customs declaration."
        ),
        "grade_labels": {
            "A1": "A1 - Export Ready - Top Quality",
            "A2": "A2 - Exportable with Disclosure",
            "B1": "B1 - Domestic Market Only",
            "B2": "B2 - Domestic / Scrap Grade",
        },
        "trust_statement": (
            "This document is generated by StoneVision AI using Google Gemini "
            "Vision technology. Each scan is timestamped and cryptographically "
            "referenced. Scan the QR code to verify authenticity online."
        ),
    },
    "AR": {
        "catalog_title":     "KATALOG AL-GRANIT",
        "ai_verified":       "MUTAHAQAQ BIL-DHAKA AL-ISHTIRAKI",
        "powered_by":        "Powered by Google Gemini Vision AI",
        "exporter":          "Al-Musaddir",
        "scan_id":           "Raqm Al-Mash",
        "variety":           "Naw Al-Hajar",
        "grade":             "Darajat Al-Jawda",
        "length":            "Al-Tul (taqdir)",
        "width":             "Al-Ard (taqdir)",
        "height":            "Al-Irtifa (taqdir)",
        "volume":            "Al-Hajm (taqdir)",
        "weight":            "Al-Wazn (taqdir)",
        "value":             "Al-Qima (taqdir)",
        "markets":           "Aswaq Al-Tasdir",
        "confidence":        "Thiqa Al-Dhaka Al-Ishtiraki",
        "variety_conf":      "Tahqiq Al-Naw",
        "dims_conf":         "Al-Abiad",
        "reference_stick":   "Asaa Al-Marja",
        "detected":          "Maktashaf",
        "not_detected":      "Ghayr Maktashaf - Yatahaqaq",
        "verify_online":     "TAHAQAQ ALAYN",
        "scan_qr":           "Imsha QR للتحقق من هذه الشهادة عبر الإنترنت",
        "disclaimer_title":  "TANBIH MUHIM",
        "disclaimer_body":   (
            "Jami al-abiad wa-tahqiqat al-naw wa-taqdirat al-qima hi taqdirat "
            "AI min tahlil al-suwwar. Yajib al-tahaqaq al-mustaqil qabla ay aqd."
        ),
        "grade_labels": {
            "A1": "A1 - Jaz Lil-Tasdir - Jawda Aliya",
            "A2": "A2 - Jaz Lil-Tasdir Ma Ifsha",
            "B1": "B1 - Lil-Suq Al-Mahalli Faqat",
            "B2": "B2 - Mahalli / Khurda",
        },
        "trust_statement": (
            "Tamma insha hadha al-mustand biwasitat StoneVision AI. "
            "Imsha ramz QR lil-tahaqaq min al-asala alayn."
        ),
    },
    "ZH": {
        "catalog_title":     "HUAGANG KUAI MULU",
        "ai_verified":       "AI YI YAN ZHENG",
        "powered_by":        "Powered by Google Gemini Vision AI",
        "exporter":          "Chu Kou Shang",
        "scan_id":           "Sao Miao ID",
        "variety":           "Shi Cai Pin Zhong",
        "grade":             "Zhi Liang Deng Ji",
        "length":            "Chang Du (gu ji)",
        "width":             "Kuan Du (gu ji)",
        "height":            "Gao Du (gu ji)",
        "volume":            "Ti Ji (gu ji)",
        "weight":            "Zhong Liang (gu ji)",
        "value":             "Jia Zhi (gu ji)",
        "markets":           "Chu Kou Shi Chang",
        "confidence":        "AI Zhi Xin Du",
        "variety_conf":      "Pin Zhong Shi Bie",
        "dims_conf":         "Chi Cun",
        "reference_stick":   "Can Kao Chi",
        "detected":          "Yi Jian Ce",
        "not_detected":      "Wei Jian Ce - Qing He Shi",
        "verify_online":     "ZAI XIAN YAN ZHENG",
        "scan_qr":           "Sao Miao QR Ma Yi Zai Xian Yan Zheng Ci Zheng Shu",
        "disclaimer_title":  "ZHONG YAO SHENG MING",
        "disclaimer_body":   (
            "Suo You Chi Cun, Pin Zhong He Jia Zhi Gu Ji Jun Wei AI Sheng Cheng. "
            "Zhe Xie Jin Wei Gu Ji - Fei Ren Zheng Ce Liang. "
            "Wu Cha Fan Wei: +/-5% Zhi +/-15%. "
            "Zai Ren He Shang Ye He Tong Qian Bi Xu Du Li He Shi."
        ),
        "grade_labels": {
            "A1": "A1 - Ke Chu Kou - Ding Ji Zhi Liang",
            "A2": "A2 - Ke Chu Kou Dai Shuo Ming",
            "B1": "B1 - Jin Nei Xiao Shi Chang",
            "B2": "B2 - Nei Xiao / Bian Jiao Liao",
        },
        "trust_statement": (
            "Ben Wen Jian You StoneVision AI Shi Yong Google Gemini Vision "
            "Ji Shu Sheng Cheng. Sao Miao QR Ma Yi Zai Xian Yan Zheng."
        ),
    },
    "PL": {
        "catalog_title":     "KATALOG BLOKOW GRANITOWYCH",
        "ai_verified":       "ZWERYFIKOWANO PRZEZ AI",
        "powered_by":        "Powered by Google Gemini Vision AI",
        "exporter":          "Eksporter",
        "scan_id":           "ID Skanu",
        "variety":           "Odmiana Kamienia",
        "grade":             "Klasa Jakosci",
        "length":            "Dlugosc (szac.)",
        "width":             "Szerokosc (szac.)",
        "height":            "Wysokosc (szac.)",
        "volume":            "Objetosc (szac.)",
        "weight":            "Waga (szac.)",
        "value":             "Wartosc (szac.)",
        "markets":           "Rynki Eksportowe",
        "confidence":        "Pewnosc AI",
        "variety_conf":      "ID Odmiany",
        "dims_conf":         "Wymiary",
        "reference_stick":   "Kij Odniesienia",
        "detected":          "Wykryto",
        "not_detected":      "Nie wykryto - sprawdz",
        "verify_online":     "WERYFIKUJ ONLINE",
        "scan_qr":           "Zeskanuj kod QR aby zweryfikowac ten certyfikat online",
        "disclaimer_title":  "WAZNE ZASTRZEZENIE",
        "disclaimer_body":   (
            "Wszystkie wymiary, identyfikacje odmian i szacunki wartosci sa "
            "generowane przez AI z analizy fotograficznej. "
            "To sa TYLKO SZACUNKI - nie certyfikowane pomiary. "
            "Margines bledu: +/-5% do +/-15%. "
            "Nalezy niezaleznie zweryfikowac przed zawarciem jakiejkolwiek umowy handlowej."
        ),
        "grade_labels": {
            "A1": "A1 - Gotowy do Eksportu - Najwyzsza Jakosc",
            "A2": "A2 - Eksportowalny z Ujawnieniem",
            "B1": "B1 - Tylko Rynek Krajowy",
            "B2": "B2 - Krajowy / Zlom",
        },
        "trust_statement": (
            "Ten dokument zostal wygenerowany przez StoneVision AI przy uzyciu "
            "technologii Google Gemini Vision. "
            "Zeskanuj kod QR aby zweryfikowac autentycznosc online."
        ),
    },
    "TA": {
        "catalog_title":     "KARANAI THAKAVAL PATTIYAL",
        "ai_verified":       "AI SARIGAPPADUTHAPATTADU",
        "powered_by":        "Google Gemini Vision AI Moolamaga",
        "exporter":          "Errumatiar",
        "scan_id":           "Scan ID",
        "variety":           "Kal Vagaipadu",
        "grade":             "Thara Nilai",
        "length":            "Neelamam (madipu)",
        "width":             "Agalam (madipu)",
        "height":            "Uyaram (madipu)",
        "volume":            "Alavai (madipu)",
        "weight":            "Edai (madipu)",
        "value":             "Mathi (madipu)",
        "markets":           "Errumathu Sandhaigal",
        "confidence":        "AI Nambikkai",
        "variety_conf":      "Vagaipadu Arival",
        "dims_conf":         "Alavugal",
        "reference_stick":   "Alavai Kol",
        "detected":          "Kandupidikkappattathu",
        "not_detected":      "Kandupidikkavillai - Sariyapaar",
        "verify_online":     "ONLINE SARIYAPAAR",
        "scan_qr":           "QR Code scan seithu online sariyapaarkavum",
        "disclaimer_title":  "MUKKIYA VILAMBARAKKATHAI",
        "disclaimer_body":   (
            "Ella alavugalum vagaipadum mathi madippugalum Google Gemini "
            "Vision moolamaga photo paarvaiyil irundu AI urupadi seyyappattathu. "
            "Ivai madippugal mattume - saragamana alavu illai. "
            "Thavaruppu: +/-5% muthal +/-15% varai. "
            "Ethavadu vanigak opandam seivatharkku munbu thalainilayaana sariyapaar seyyappada vendum."
        ),
        "grade_labels": {
            "A1": "A1 - Errumathu Thayaar - Mela Tharam",
            "A2": "A2 - Therivippoadu Errumathukku Thagudhi",
            "B1": "B1 - Naadu Sandhai Mattume",
            "B2": "B2 - Naadu / Kuppai",
        },
        "trust_statement": (
            "Indha aavananam StoneVision AI moolamaga Google Gemini Vision "
            "tholviyalai payandrithu uruvakkappattathu. "
            "Online sarigappadutha QR code scan seyyavum."
        ),
    },
}


def generate_multilingual_pdf(
    stone: dict,
    company: dict,
    language: str = "EN"
) -> bytes:
    """
    Generate multilingual PDF catalog.
    language: EN | TA | AR | ZH | PL
    """
    lang = language.upper()
    if lang not in TRANSLATIONS:
        lang = "EN"
    T = TRANSLATIONS[lang]

    # ── Safe extractors ──────────────────────────────────────
    def _s(k, d=""): v = stone.get(k); return str(v).strip() if v else d
    def _f(k, d=0.0):
        try: v = float(stone.get(k) or d); return d if v != v else v
        except: return d
    def _i(k, d=0):
        try: v = stone.get(k); return int(v) if v else d
        except: return d

    scan_code = _s("scan_code", "SV-UNKNOWN")
    variety   = _s("variety",   "Unknown Granite")
    grade     = _s("quality_grade", "A2")
    grade     = grade if grade in ("A1","A2","B1","B2") else "A2"
    L, W, H   = _f("length_cm"), _f("width_cm"), _f("height_cm")
    vol_m3    = _f("volume_m3"); vol_cft = _f("volume_cft")
    weight    = _i("estimated_weight_kg")
    vpf       = _i("value_per_cft_inr")
    total_val = _i("total_value_inr")
    markets   = ", ".join(stone.get("export_markets") or []) or "-"
    stick_ok  = stone.get("reference_stick_ok", True)
    pub_link  = _s("public_link", "")
    scanned_at = (_s("scanned_at","")[:10] or "-")
    ai_flags  = [f for f in (stone.get("ai_flags") or []) if isinstance(f, str)]

    _vc = _f("variety_confidence", 0)
    _mc = _f("measurement_confidence", 0)
    v_conf = max(0, min(int(_vc if _vc > 1 else _vc * 100), 100))
    m_conf = max(0, min(int(_mc if _mc > 1 else _mc * 100), 100))

    co_name     = (company.get("name") or "Granite Exporter")[:60]
    co_city     = (company.get("city") or "Melur")[:30]
    is_verified = bool(company.get("is_verified", False))

    # ── PDF ──────────────────────────────────────────────────
    # Load native font for this language
    font_path = FONTS.get(lang, FONTS["EN"])
    font_name = FONT_NAMES.get(lang, "NotoSans")
    _font_loaded = False

    class MultiPDF(FPDF):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            # Load native Unicode font
            nonlocal _font_loaded, font_name, font_path
            try:
                if os.path.exists(font_path):
                    self.add_font(font_name, "", font_path, uni=True)
                    self.add_font(font_name, "B", font_path, uni=True)
                    _font_loaded = True
                    print(f"  Loaded native font: {font_name} for {lang}")
            except Exception as e:
                print(f"  Font warning: {e}")
                _font_loaded = False

        def native_font(self, size: float, bold: bool = False):
            """Set native Unicode font."""
            nonlocal _font_loaded, font_name
            if _font_loaded:
                try:
                    self.set_font(font_name, "B" if bold else "", size)
                    return
                except Exception:
                    pass
            self.set_font("Helvetica", "B" if bold else "", size)

        def latin_font(self, size: float, bold: bool = False):
            """Always use Latin font for codes, numbers, URLs."""
            self.set_font("Helvetica", "B" if bold else "", size)

        def cell_native(self, w, h, txt="", border=0, align="L", fill=False, new_x=XPos.RIGHT, new_y=YPos.TOP):
            """Smart cell: use Latin font for ASCII-only text."""
            is_ascii = all(ord(c) < 128 for c in str(txt))
            if is_ascii or lang in ("EN", "PL"):
                self.set_font("Helvetica", self.font_style, self.font_size_pt)
            self.cell(w, h, str(txt), border=border, align=align, fill=fill, new_x=new_x, new_y=new_y)

        def set_font_auto(self, text: str, size: float, bold: bool = False):
            """Auto-select font: native for translated text, Helvetica for ASCII."""
            is_ascii = all(ord(c) < 128 for c in str(text))
            if is_ascii or lang in ("EN", "PL"):
                self.set_font("Helvetica", "B" if bold else "", size)
            else:
                self.native_font(size, bold)

        def header(self):
            # Gold stripe
            self.set_fill_color(*GOLD)
            self.rect(0, 0, 210, 6, style="F")
            # AI Verified badge top right
            self.set_fill_color(*DARK)
            self.set_text_color(*GOLD)
            self.set_font("Helvetica", "B", 7)  # Badge always Latin
            self.set_xy(140, 8)
            self.cell(56, 5, f"  {T['ai_verified']}  ", align="C", fill=True)
            # Google Gemini line
            self.native_font(6)
            self.set_text_color(*GRAY)
            self.set_xy(140, 14)
            self.cell(56, 4, T["powered_by"], align="C")
            # Exporter name
            self.set_xy(10, 9)
            self.native_font(13, True)
            self.set_text_color(*DARK)
            self.cell(125, 7, co_name.upper())
            self.set_xy(10, 17)
            self.native_font(7)
            self.set_text_color(*GRAY)
            badge = "  [StoneVision Certified]" if is_verified else ""
            self.cell(125, 4, f"{co_city}, Tamil Nadu, India{badge}")
            # Divider
            self.set_draw_color(*GOLD)
            self.set_line_width(0.4)
            self.line(10, 23, 200, 23)
            self.ln(8)

        def footer(self):
            self.set_y(-20)
            self.native_font(6, True)
            self.set_text_color(*RED)
            self.cell(0, 4,
                "AI ESTIMATE ONLY - NOT certified measurement. "
                "Verify independently before commercial use.",
                align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.native_font(6)
            self.set_text_color(*GRAY)
            self.cell(0, 4,
                f"{SV_BRAND}  |  {SV_WEBSITE}  |  {SV_EMAIL}  |  {SV_CITY}  |  Lang: {lang}",
                align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            yr = datetime.now(timezone.utc).year
            today = datetime.now(timezone.utc).strftime("%d %b %Y")
            self.native_font(5.5)
            self.set_text_color(*GRAY)
            self.cell(0, 3.5,
                f"Page {self.page_no()}  |  {today}  |  "
                f"Copyright (c) {yr} {SV_BRAND}. All rights reserved.",
                align="C")

    pdf = MultiPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=24)
    pdf.set_margins(10, 10, 10)
    pdf.add_page()

    # ── Catalog title ────────────────────────────────────────
    pdf.native_font(9, True)
    pdf.set_text_color(*GRAY)
    pdf.cell(0, 5, f"{T['catalog_title']}  |  #{scan_code}  |  {scanned_at}",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(1)

    # ── Variety + Grade ──────────────────────────────────────
    pdf.native_font(18, True)
    pdf.set_text_color(*DARK)
    pdf.cell(140, 10, variety, new_x=XPos.RIGHT, new_y=YPos.TOP)
    # Grade badge
    badge_col = GREEN if grade=="A1" else AMBER if grade=="A2" else RED
    pdf.set_fill_color(*badge_col)
    pdf.set_text_color(*WHITE)
    pdf.native_font(9, True)
    pdf.cell(50, 10, f"  {T['grade']}: {grade}", fill=True,
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.native_font(7)
    pdf.set_text_color(*GRAY)
    grade_lbl = T["grade_labels"].get(grade, "")
    pdf.cell(0, 4, grade_lbl, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # ── Confidence trust bar ─────────────────────────────────
    pdf.set_fill_color(*DARK)
    pdf.set_text_color(*GOLD)
    pdf.native_font(7, True)
    pdf.cell(0, 5,
        f"  {T['confidence']}: {T['variety_conf']} {v_conf}%  |  "
        f"{T['dims_conf']} {m_conf}%  |  "
        f"{T['reference_stick']}: {T['detected'] if stick_ok else T['not_detected']}",
        fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # ── AI Flag warning ──────────────────────────────────────
    if ai_flags:
        pdf.set_fill_color(255, 235, 220)
        pdf.set_draw_color(*RED)
        pdf.set_line_width(0.3)
        pdf.native_font(7, True)
        pdf.set_text_color(*RED)
        flags_txt = "  FLAGS: " + "  |  ".join(f.replace("_"," ") for f in ai_flags)
        pdf.cell(0, 6, flags_txt[:90], fill=True, border=1,
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(3)

    # ── Dimensions ───────────────────────────────────────────
    pdf.native_font(7, True)
    pdf.set_text_color(*GRAY)
    pdf.cell(0, 4, "ESTIMATED DIMENSIONS  (+/-5 to 15% error margin)",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(1)
    for lbl_key, val in [("length",L),("width",W),("height",H)]:
        _draw_dim(pdf, T[lbl_key], f"{val:.1f}" if val else "-", "cm")
    pdf.ln(22)

    # ── Details table ────────────────────────────────────────
    pdf.native_font(7, True)
    pdf.set_text_color(*GRAY)
    pdf.cell(0, 4, T["catalog_title"], new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(1)

    rows = [
        (T["variety"],    variety),
        (T["exporter"],   f"{co_name}, {co_city}"),
        (T["volume"],     f"{vol_m3} m3  /  {vol_cft} cft"),
        (T["weight"],     f"{weight:,} kg" if weight else "-"),
        (T["value"],      f"Rs.{vpf:,}/cft  |  Rs.{total_val/100000:.1f}L" if vpf else "-"),
        (T["markets"],    markets),
        ("AI Source",     "Google Gemini 1.5 Flash Vision"),
        (T["scan_id"],    scan_code),
        ("Platform",      f"{SV_BRAND}  |  {SV_WEBSITE}"),
    ]
    for i, (k, v) in enumerate(rows):
        bg = LGRAY if i % 2 == 0 else WHITE
        pdf.set_fill_color(*bg)
        pdf.native_font(7.5)
        pdf.set_text_color(*GRAY)
        pdf.cell(55, 6, f"  {k}", fill=True)
        pdf.set_text_color(*DARK)
        pdf.cell(0, 6, f"  {v}", fill=True,
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # ── Trust statement ──────────────────────────────────────
    pdf.set_fill_color(*DARK)
    pdf.native_font(7)
    pdf.set_text_color(*GOLD)
    pdf.multi_cell(0, 4.5, f"  {T['trust_statement']}", fill=True)
    pdf.ln(3)

    # ── QR Code + verify link ────────────────────────────────
    if pub_link:
        qr_y = pdf.get_y()
        try:
            buf = _qr(pub_link)
            pdf.native_font(7, True)
            pdf.set_text_color(*GRAY)
            pdf.cell(145, 5, f"{T['verify_online']}  -  {T['scan_qr']}",
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.native_font(7)
            pdf.set_text_color(*DARK)
            pdf.cell(145, 5, pub_link[:70],
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.image(buf, x=162, y=qr_y, w=30, h=30)
        except Exception:
            pass
        pdf.ln(8)

    # ── Legal disclaimer ─────────────────────────────────────
    pdf.set_fill_color(255, 244, 244)
    pdf.set_draw_color(*RED)
    pdf.set_line_width(0.4)
    pdf.native_font(7, True)
    pdf.set_text_color(*RED)
    pdf.cell(0, 6, f"  ! {T['disclaimer_title']}",
             fill=True, border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.native_font(6.5)
    pdf.set_text_color(*GRAY)
    pdf.multi_cell(0, 4, f"  {T['disclaimer_body']}", fill=True, border=1)
    pdf.ln(3)

    # ── Powered by block ─────────────────────────────────────
    pdf.set_fill_color(*DARK)
    pdf.native_font(7.5, True)
    pdf.set_text_color(*GOLD)
    pdf.cell(0, 6, f"  {SV_BRAND}  -  Granite Intelligence  |  {SV_WEBSITE}",
             fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output())


def _draw_dim(pdf: FPDF, label: str, value: str, unit: str):
    x, y, w = pdf.get_x(), pdf.get_y(), 54
    pdf.set_fill_color(*LGRAY)
    pdf.rect(x, y, w-3, 18, style="F")
    pdf.set_draw_color(*GOLD)
    pdf.set_line_width(0.2)
    pdf.rect(x, y, w-3, 18)
    pdf.set_xy(x, y+1);  pdf.native_font(6.5); pdf.set_text_color(*GRAY)
    pdf.cell(w-3, 4, label, align="C")
    pdf.set_xy(x, y+5.5); pdf.native_font(13, True); pdf.set_text_color(*DARK)
    pdf.cell(w-3, 7, value, align="C")
    pdf.set_xy(x, y+13);  pdf.native_font(6.5); pdf.set_text_color(*GRAY)
    pdf.cell(w-3, 4, f"({unit} - AI est.)", align="C")
    pdf.set_xy(x+w, y)


def _qr(url: str) -> io.BytesIO:
    qr = qrcode.QRCode(version=2,
                       error_correction=qrcode.constants.ERROR_CORRECT_M,
                       box_size=5, border=2)
    qr.add_data(url)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf
