"use client";
import { useEffect, useState, Suspense } from "react";
import { useParams } from "next/navigation";

interface PDFRecord {
  pdf_id: string;
  scan_code: string;
  variety: string;
  grade: string;
  company_name: string;
  generated_at: string;
  language: string;
  verified: boolean;
  url: string;
}

function VerifyContent() {
  const params = useParams();
  const pdf_id = params?.pdf_id as string;
  const [record, setRecord] = useState<PDFRecord|null>(null);
  const [loading, setLoading] = useState(true);
  const [valid, setValid] = useState<boolean|null>(null);

  useEffect(() => {
    if (!pdf_id) return;
    fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/verify/${pdf_id}`)
      .then(r => r.json())
      .then(d => {
        setRecord(d);
        setValid(d.verified === true);
        setLoading(false);
      })
      .catch(() => { setValid(false); setLoading(false); });
  }, [pdf_id]);

  if (loading) return (
    <div style={{minHeight:"100vh",background:"#0a0908",display:"flex",alignItems:"center",justifyContent:"center"}}>
      <div style={{width:28,height:28,border:"2px solid #c9a84c",borderTopColor:"transparent",borderRadius:"50%",animation:"spin 1s linear infinite"}}/>
      <style>{"@keyframes spin{to{transform:rotate(360deg)}}"}</style>
    </div>
  );

  return (
    <div style={{minHeight:"100vh",background:"#0a0908",color:"#f0ebe0",fontFamily:"sans-serif",display:"flex",alignItems:"center",justifyContent:"center",padding:16}}>
      <div style={{maxWidth:440,width:"100%"}}>

        {/* Header */}
        <div style={{textAlign:"center",marginBottom:24}}>
          <div style={{fontSize:32,color:"#c9a84c",marginBottom:6}}>◈</div>
          <div style={{fontSize:11,color:"#4a4438",letterSpacing:3,textTransform:"uppercase"}}>StoneVision AI · Document Verification</div>
        </div>

        {/* Result card */}
        <div style={{
          background:"#1a1814",
          border:`1px solid ${valid?"rgba(45,158,107,.4)":"rgba(192,57,43,.4)"}`,
          borderRadius:20,padding:28,textAlign:"center",
        }}>
          <div style={{fontSize:56,marginBottom:16}}>{valid?"✅":"❌"}</div>
          <h2 style={{fontSize:22,color:"#f0ebe0",marginBottom:8}}>
            {valid?"Document Verified":"Document Not Found"}
          </h2>
          <p style={{fontSize:13,color:"#8a8070",lineHeight:1.6,marginBottom:20}}>
            {valid
              ? "This PDF was generated by StoneVision AI and has not been tampered with."
              : "This document ID could not be verified. It may have been deleted or the link is incorrect."}
          </p>

          {valid && record && (
            <div style={{background:"#242118",border:"1px solid #3a3528",borderRadius:12,padding:16,textAlign:"left",marginBottom:20}}>
              <div style={{fontSize:10,color:"#c9a84c",letterSpacing:2,marginBottom:10}}>VERIFIED DOCUMENT DETAILS</div>
              {[
                ["Scan Code",    record.scan_code],
                ["Variety",      record.variety],
                ["Grade",        record.grade],
                ["Exporter",     record.company_name],
                ["Language",     record.language],
                ["Generated",    new Date(record.generated_at).toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"})],
                ["Verified By",  "StoneVision AI · Google Gemini Vision"],
              ].map(([k,v])=>(
                <div key={k} style={{display:"flex",justifyContent:"space-between",padding:"7px 0",borderBottom:"1px solid #2a2620",fontSize:12}}>
                  <span style={{color:"#6a6050"}}>{k}</span>
                  <span style={{color:"#f0ebe0",fontWeight:500,textAlign:"right",maxWidth:"55%"}}>{v}</span>
                </div>
              ))}
            </div>
          )}

          <div style={{
            background:valid?"rgba(45,158,107,.08)":"rgba(192,57,43,.08)",
            border:`1px solid ${valid?"rgba(45,158,107,.2)":"rgba(192,57,43,.2)"}`,
            borderRadius:10,padding:"10px 14px",fontSize:11,
            color:valid?"#2d9e6b":"#e74c3c",lineHeight:1.6,textAlign:"left",marginBottom:16,
          }}>
            {valid
              ? "⚠️ All dimensions are AI estimates (±5-15%). This document confirms the scan was performed by StoneVision AI. Independent verification is required before commercial use."
              : "If you believe this is an error, contact support@stonevision.in with the document ID."}
          </div>

          <div style={{fontSize:10,color:"#3a3428"}}>
            Document ID: {pdf_id}<br/>
            Verified at: {new Date().toLocaleString("en-IN")}
          </div>
        </div>

        <div style={{textAlign:"center",marginTop:20,fontSize:11,color:"#3a3428"}}>
          ◈ StoneVision AI · Granite Intelligence · Madurai, Tamil Nadu
        </div>
      </div>
    </div>
  );
}

export default function VerifyPage() {
  return (
    <Suspense fallback={<div style={{minHeight:"100vh",background:"#0a0908",display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{color:"#c9a84c"}}>Verifying...</div></div>}>
      <VerifyContent/>
    </Suspense>
  );
}
