"use client";
import Link from "next/link";

export default function TermsPage() {
  const updated = "25 May 2026";

  const sections = [
    {
      n:"1",
      title:"Nature of Service — AI Estimation Tool Only",
      warn:true,
      body:`StoneVision AI provides an artificial intelligence tool that analyses photographs of granite blocks to estimate dimensions, identify stone variety, assign quality grades, and estimate market value. All outputs are generated by Google Gemini Vision API.

CRITICAL LEGAL NOTICE: StoneVision AI is a TECHNOLOGY PLATFORM only. We are NOT:
• A certified surveyor, inspector, or quality assurance body
• A trade agent, broker, or commercial intermediary
• A party to any transaction between buyer and seller
• Responsible for the physical condition, quantity, or quality of any goods

All AI outputs are ESTIMATES ONLY. They carry a ±5% to ±15% error margin.`
    },
    {
      n:"2",
      title:"No Liability — Absolute Disclaimer",
      warn:true,
      body:`TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, STONEVISION AI, ITS DIRECTORS, EMPLOYEES, AGENTS, AND TECHNOLOGY PROVIDERS SHALL NOT BE LIABLE FOR:

(a) Any financial loss, including loss of profit, revenue, business, or anticipated savings arising from reliance on AI-generated estimates

(b) Any loss arising from a transaction where goods received differ from AI estimates, including but not limited to: incorrect dimensions, wrong stone variety, incorrect quality grade, wrong weight, or wrong market value

(c) Any customs delays, demurrage charges, port storage fees, or shipping costs arising from document discrepancies

(d) Rejection of shipments, Letters of Credit, or bank documents based on StoneVision AI outputs

(e) Any dispute between buyer and seller where StoneVision AI outputs were used as evidence

(f) Physical loss, damage, or deterioration of goods during transit

(g) Any indirect, incidental, special, consequential, or punitive damages whatsoever

THIS LIMITATION APPLIES WHETHER THE CLAIM IS BASED IN CONTRACT, TORT, NEGLIGENCE, PRODUCT LIABILITY, OR ANY OTHER LEGAL THEORY, EVEN IF STONEVISION AI HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

StoneVision AI's total cumulative liability to any user under any circumstances shall not exceed the subscription fees paid by that user in the three (3) months immediately preceding the claim. Under no circumstances shall this amount exceed USD $500 (five hundred United States dollars).`
    },
    {
      n:"3",
      title:"No Reimbursement for Transaction Losses",
      warn:true,
      body:`StoneVision AI does NOT reimburse, compensate, or indemnify any user for:

• Losses on commercial transactions where AI estimates were used
• Costs of returning or re-shipping incorrect goods
• Demurrage, port, or customs charges
• Losses from rejected Letters of Credit
• Losses from quality disputes with counterparties
• Lost profits from cancelled orders
• Legal costs in disputes with third parties

By using StoneVision AI, you acknowledge that all commercial decisions, including the decision to purchase or sell goods, transfer money, or ship goods, are made entirely at your own risk and at your own commercial judgment.

StoneVision AI is a tool to assist in decision-making. It is NOT a guarantee of accuracy and does NOT replace independent professional verification.`
    },
    {
      n:"4",
      title:"Mandatory Independent Verification",
      body:`Before entering any commercial contract, transferring any funds, or shipping any goods based on StoneVision AI outputs, you MUST:

(a) Independently verify all dimensions using calibrated measuring tools (steel tape, laser measure) operated by a qualified person

(b) Engage an independent third-party inspection agency (such as SGS, Bureau Veritas, or equivalent) for high-value orders exceeding $10,000

(c) Confirm stone variety and grade with a qualified geologist or stone expert

(d) Ensure all export documentation contains verified, certified measurements compliant with applicable law

(e) Disclose to all counterparties that preliminary measurements were AI-estimated

Failure to independently verify before transacting does not create any liability for StoneVision AI.`
    },
    {
      n:"5",
      title:"Physical Audit Service Terms",
      body:`Where StoneVision AI arranges a Physical Audit Service:

(a) The audit is performed by an independent third-party inspector contracted by StoneVision AI. The inspector is not an employee of StoneVision AI.

(b) The physical audit report represents the inspector's best professional assessment at the time of inspection. It is NOT a legal certification and does NOT create liability for StoneVision AI for any variance discovered after shipment.

(c) StoneVision AI earns a service facilitation fee (commission) for connecting buyers and sellers and arranging inspections. This fee is earned for the SERVICE of connection and arrangement, not as a guarantee of outcome.

(d) The 5% commission charged on transaction value is a SERVICE FEE for platform access, document generation, and audit facilitation. It does not constitute insurance, guarantee, warranty, or indemnification of any kind.

(e) If an audit inspector's report contains errors, liability is limited to a refund of the audit service fee only, not to the value of the underlying transaction.`
    },
    {
      n:"6",
      title:"Commercial Use Restrictions",
      body:`You agree that you will:

(a) ALWAYS verify AI estimates with a qualified professional before signing any commercial contract
(b) NEVER present AI estimates as certified measurements to buyers, banks, or customs authorities without independent verification
(c) DISCLOSE to all counterparties that measurements are AI-estimated, subject to ±5-15% variance
(d) NOT use StoneVision AI output as sole legal evidence in commercial disputes
(e) Comply with all applicable export-import regulations of India and your country
(f) NOT use StoneVision AI for any unlawful purpose including customs fraud, money laundering, or trade-based money laundering`
    },
    {
      n:"7",
      title:"QR Verification — Authenticity Only",
      body:`The QR code embedded in StoneVision AI PDF documents verifies only that:

(a) The document was generated by StoneVision AI's platform
(b) The document has not been digitally altered since generation
(c) The scan was performed on the stated date

QR verification does NOT certify the accuracy of dimensions, grade, or value estimates contained in the document. It is an authenticity check only, not a quality or measurement certification.`
    },
    {
      n:"8",
      title:"Governing Law and Jurisdiction",
      body:`These Terms are governed by the laws of India. Any dispute arising from the use of StoneVision AI shall be subject to the exclusive jurisdiction of the courts of Madurai, Tamil Nadu, India.

For disputes involving international users: You agree that any claim against StoneVision AI shall be brought exclusively in Indian courts under Indian law, and you waive any right to bring claims in your home country's courts.

If any provision of these Terms is found invalid by a court, the remaining provisions continue in full force.`
    },
    {
      n:"9",
      title:"Dispute Resolution — Arbitration First",
      body:`Before initiating any legal proceedings, you agree to first attempt resolution through:

(a) Written notice to support@stonevision.in describing the dispute in detail
(b) Good faith negotiation for a period of 30 days from notice
(c) If unresolved, binding arbitration under the Arbitration and Conciliation Act, 1996 (India)
(d) Arbitration to be conducted in Madurai, Tamil Nadu in the English language

Class action lawsuits and class-wide arbitration are expressly waived. All claims must be brought individually.`
    },
    {
      n:"10",
      title:"Indemnification by User",
      body:`You agree to indemnify, defend, and hold harmless StoneVision AI, its directors, officers, employees, and agents from any claims, damages, losses, liabilities, and expenses (including legal fees) arising from:

(a) Your use of StoneVision AI outputs in commercial transactions
(b) Your breach of these Terms
(c) Your violation of any applicable law or regulation
(d) Any claim by a third party that arose from your reliance on AI-generated estimates
(e) Any dispute between you and your commercial counterparty where StoneVision AI outputs were used`
    },
    {
      n:"11",
      title:"Subscription — No Refund Policy",
      body:`Subscription fees paid to StoneVision AI are non-refundable except where required by applicable law.

Cancellation of subscription stops future charges but does not entitle you to a refund of fees already paid.

Transaction-based commission fees (audit facilitation) are earned upon completion of the facilitation service and are non-refundable regardless of transaction outcome.`
    },
    {
      n:"12",
      title:"Acceptance of These Terms",
      warn:false,
      body:`By creating an account, paying a subscription, or using any feature of StoneVision AI, you confirm that:

(a) You have read and understood these Terms in full
(b) You accept that StoneVision AI outputs are AI estimates only
(c) You accept that StoneVision AI has no liability for transaction losses
(d) You are authorised to enter these Terms on behalf of your company
(e) You are at least 18 years of age

If you do not accept these Terms, do not use StoneVision AI.

Last updated: 25 May 2026
StoneVision AI · Madurai, Tamil Nadu, India
support@stonevision.in`
    },
  ];

  return (
    <div style={{minHeight:"100vh",background:"#0a0908",color:"#ede8e0",fontFamily:"'Manrope',sans-serif",paddingBottom:64}}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;1,300;1,400&family=Manrope:wght@300;400;500&display=swap');
      `}</style>

      <nav style={{position:"sticky",top:0,zIndex:50,background:"rgba(10,9,8,.97)",backdropFilter:"blur(20px)",borderBottom:"1px solid rgba(184,146,42,.1)",padding:"14px 24px",display:"flex",alignItems:"center",justifyContent:"space-between"}}>
        <Link href="/" style={{display:"flex",alignItems:"center",gap:10,textDecoration:"none"}}>
          <img src="/logo.png" alt="StoneVision AI" style={{height:32,width:"auto",objectFit:"contain"}}/>
          <span style={{fontFamily:"'Cormorant Garamond',Georgia,serif",fontSize:16,fontWeight:300,color:"#ede8e0",letterSpacing:".1em",textTransform:"uppercase"}}>StoneVision AI</span>
        </Link>
        <span style={{fontSize:10,color:"#3a3830",letterSpacing:".08em"}}>Last updated: {updated}</span>
      </nav>

      <div style={{maxWidth:720,margin:"0 auto",padding:"48px 24px"}}>

        {/* Header */}
        <div style={{marginBottom:48,paddingBottom:32,borderBottom:"1px solid rgba(184,146,42,.1)"}}>
          <div style={{fontSize:9,letterSpacing:".22em",textTransform:"uppercase",color:"rgba(184,146,42,.5)",marginBottom:16,display:"flex",alignItems:"center",gap:8}}>
            <span style={{width:20,height:"1px",background:"rgba(184,146,42,.3)",display:"inline-block"}}/>
            Legal Document
          </div>
          <h1 style={{fontFamily:"'Cormorant Garamond',Georgia,serif",fontSize:44,fontWeight:300,color:"#ede8e0",letterSpacing:".02em",marginBottom:12,lineHeight:1.1}}>
            Terms of Use
          </h1>
          <p style={{fontSize:13,color:"#3a3830",fontWeight:300,lineHeight:1.7,maxWidth:560}}>
            These Terms govern your use of the StoneVision AI platform. Read them carefully. By using the platform you accept these Terms in full. If you do not accept, do not use the platform.
          </p>

          {/* Critical warning box */}
          <div style={{marginTop:24,background:"rgba(180,50,40,.08)",border:"1px solid rgba(180,50,40,.2)",borderRadius:6,padding:"16px 20px"}}>
            <div style={{fontSize:10,letterSpacing:".18em",textTransform:"uppercase",color:"rgba(200,80,60,.8)",fontWeight:500,marginBottom:8}}>
              Critical notice before you continue
            </div>
            <p style={{fontSize:13,color:"rgba(200,80,60,.7)",fontWeight:300,lineHeight:1.7,margin:0}}>
              StoneVision AI outputs are AI estimates only. They are NOT certified measurements. StoneVision AI does not reimburse losses on commercial transactions. All commercial decisions are made at your own risk. Independent verification is mandatory before any transaction.
            </p>
          </div>
        </div>

        {/* Table of contents */}
        <div style={{background:"rgba(184,146,42,.04)",border:"1px solid rgba(184,146,42,.1)",borderRadius:6,padding:"16px 20px",marginBottom:40}}>
          <div style={{fontSize:10,letterSpacing:".18em",textTransform:"uppercase",color:"rgba(184,146,42,.5)",marginBottom:12,fontWeight:500}}>Contents</div>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"4px 24px"}}>
            {sections.map(s=>(
              <a key={s.n} href={"#s"+s.n} style={{fontSize:12,color:"#5a5850",textDecoration:"none",padding:"3px 0",transition:"color .15s"}}
                onMouseEnter={e=>(e.currentTarget.style.color="#b8922a")}
                onMouseLeave={e=>(e.currentTarget.style.color="#5a5850")}>
                {s.n}. {s.title}
              </a>
            ))}
          </div>
        </div>

        {/* Sections */}
        <div style={{display:"flex",flexDirection:"column",gap:0}}>
          {sections.map(s=>(
            <div key={s.n} id={"s"+s.n} style={{paddingBottom:32,marginBottom:32,borderBottom:"1px solid rgba(255,255,255,.04)"}}>
              <div style={{display:"flex",gap:16,alignItems:"flex-start",marginBottom:14}}>
                <div style={{fontFamily:"'Cormorant Garamond',Georgia,serif",fontSize:13,color:"rgba(184,146,42,.5)",fontWeight:400,letterSpacing:".1em",flexShrink:0,paddingTop:3}}>
                  {s.n.padStart(2,"0")} —
                </div>
                <h2 style={{fontFamily:"'Cormorant Garamond',Georgia,serif",fontSize:20,fontWeight:300,color:"#ede8e0",letterSpacing:".02em",lineHeight:1.2,margin:0}}>
                  {s.title}
                </h2>
              </div>
              <div style={{
                marginLeft:52,
                background:s.warn?"rgba(180,50,40,.06)":"transparent",
                border:s.warn?"1px solid rgba(180,50,40,.15)":"none",
                borderRadius:s.warn?4:0,
                padding:s.warn?"16px 18px":0,
              }}>
                {s.body.split("\n\n").map((para,i)=>(
                  <p key={i} style={{
                    fontSize:13,
                    color:s.warn?"rgba(200,80,60,.75)":"#4a4840",
                    fontWeight:300,lineHeight:1.8,
                    marginBottom:i<s.body.split("\n\n").length-1?12:0,
                    margin:i<s.body.split("\n\n").length-1?"0 0 12px":"0",
                    whiteSpace:"pre-wrap",
                  }}>
                    {para}
                  </p>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div style={{marginTop:48,paddingTop:24,borderTop:"1px solid rgba(184,146,42,.1)",textAlign:"center"}}>
          <div style={{fontFamily:"'Cormorant Garamond',Georgia,serif",fontSize:16,color:"rgba(184,146,42,.5)",marginBottom:8}}>◈ StoneVision AI</div>
          <p style={{fontSize:11,color:"#2a2820",lineHeight:1.7}}>
            Madurai, Tamil Nadu, India · support@stonevision.in<br/>
            © 2026 StoneVision AI · All rights reserved
          </p>
          <Link href="/" style={{display:"inline-block",marginTop:16,fontSize:11,color:"#b8922a",textDecoration:"none",letterSpacing:".08em"}}>
            Return to homepage →
          </Link>
        </div>
      </div>
    </div>
  );
}
